### ISSUE TITLE
Provide Example

### ISSUE THREAD

**Issue by brayanL** [JunctionTV/react-native-on-screen-keyboard#2]
Hi, thanks for your great Job. You can provide an example of how to use the keyboard, please. I see that the library is only a component, not a keyboard really.

**Comment by khat33b** [comment]
Hi. Thanks for the compliment. An example has been provided already in the README. See it here: https://github.com/JunctionTV/react-native-on-screen-keyboard#usage. 

yes, this is a component only which can be customized and added in a React Native program. If you wish to use an actual keyboard, you can use the one provided by Android TV.
